### ISSUE TITLE
Improve SharedFromThis and MakeShared to use 1 memory allocation instead of 2

### ISSUE THREAD

**Issue by SergiusTheBest** [SergStep/IDP#1]
`SharedFromThis` and `MakeShared` must use 1 memory allocation instead of 2.

There shouldn't be a constructor `SharedFromThis(T* testUnit)`. 

Usage:
```cpp
struct Sample : SharedFromThis<Sample>
{
};

SharedPtr<Sample> p1 = SharedPtr::MakeShared<Sample>();
SharedPtr<Sample> p2 = p1->GetShared();
```

Pay attention that `MakeShared` should work in both cases when `T` is:
- just a type
- type inherited from `SharedFromThis`

**Comment by SergStep** [comment]
[Added](https://github.com/SergStep/IDP/commit/8dcad38d9b1df4a3462119c42d41443a07ea4061) MakeShared with one memory allocation

**Comment by SergStep** [comment]
[Added](https://github.com/SergStep/IDP/commit/31da929acb647fdb5d889fe784d7fefbc9d8fcc9) SharedFromThis with one memory allocation
