### ISSUE TITLE
Remove code duplication in SharedPtr

### ISSUE THREAD

**Issue by SergiusTheBest** [SergStep/IDP#3]
Find and remove duplicated code.

**Comment by SergStep** [comment]
[Done](https://github.com/SergStep/IDP/commit/a2eaf880ab7e1b68f56f5489d78ca406835d1902)

**Comment by SergiusTheBest** [comment]
FYI: It's recommended that methods should be named as verbs. `CountDecrementionAndRelease` is a noun.
